--- 
branch: master
cache: npm
deploy: ~
github-token: $GITHUB_TOKEN
install: "npm install"
language: node_js
node_js: 11.6.0
provider: npm
scripts: "npm test, npm run build"
skip-cleanup: true
true: ~
